# -*- coding: utf-8 -*-
"""tulomba_divine_3_API_112023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JdIi15zPptDlpwYjVxee8rJuynEOS_K-

### Imports de base
"""

import pandas as pd
import requests

"""### Lecture du jeu de données

## Utilisation de l'API Edamam Food and Grocery Database
"""

# Spécifie l'URL de l'API à laquelle nous allons faire une demande
url = "https://edamam-food-and-grocery-database.p.rapidapi.com/api/food-database/v2/parser"

# Définit les paramètres de la requête. Ici, nous demandons des informations sur l'ingrédient "champagne"
querystring = {"ingr":"champagne"}

# Définit les en-têtes de la requête. Il s'agit des informations nécessaires pour l'authentification auprès de l'API
headers = {
    "X-RapidAPI-Key": "8d33c2be23msh5ec6eed68dbac24p1a44cajsn5468d7cf7e48",
    "X-RapidAPI-Host": "edamam-food-and-grocery-database.p.rapidapi.com"
}

# Envoie une requête GET à l'API avec l'URL, les en-têtes et les paramètres spécifiés, et stocke la réponse
response = requests.get(url, headers=headers, params=querystring)

# Convertit la réponse de l'API en format JSON et stocke les données dans la variable "data"
data = response.json()

data

"""#  extraction des 10 premiers produits dans un fichier “.csv”, contenant pour chaque produit les données suivantes : foodId, label, category, foodContentsLabel, image."""

import csv

# Extraire les données
data = response.json().get('hints', [])

# Ouvrir un fichier CSV pour l'écriture
with open('champagne_products.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)

    # Écrire les en-têtes
    writer.writerow(['foodId', 'label', 'category', 'foodContentsLabel', 'image'])

    # Écrire les données (les 10 premiers produits)
    for item in data[:10]:
        food = item['food']
        writer.writerow([food['foodId'], food['label'], food['category'], food.get('foodContentsLabel', ''), food.get('image', '')])

    print("Fichier CSV créé avec succès.")

# Chemin vers le fichier CSV
file_path = 'champagne_products.csv'

# Lire le fichier CSV
df_api = pd.read_csv(file_path)

# Afficher les premières lignes du DataFrame
df_api

"""- les résultats sont cohérents avec l'ingrédient champagne"""